void Task1 (std::string direct);
void dop (std::string& str);
void zeroone (int num, std::string& str);
void Sum (std::string str1, std::string str2, std::string& res);
void Sum3 (std::string str1, std::string str2, std::string& res, int num);
void raz (std::string str1, std::string str2, std::string& res, int num);
bool isDel(int number, int num);
void Table30 (bool arrayTF[30][5]);
void DorLgroup (bool arrayTF[30][5], int &group);
void Table16 (bool arrayTF16[16][4], int start);
void DorL16 (bool arrayTF16[16][4], int start);
void Table8 (bool arrayTF8[8][3], int start);
void DorL8 (bool arrayTF8[8][3], int start);
void Table4 (bool arrayTF4[4][2], int start);
void DorL4 (bool arrayTF4[4][2], int start);
void Table30fin (bool arrayTF[30][5]);
void DorL30 (bool arrayTF[30][5]);